FROM python:3.9-slim

WORKDIR /app
COPY logging_service.py observer.py /app/
RUN apt-get update && apt-get install -y curl && pip install flask requests

VOLUME ["/logs"]
EXPOSE 7002
CMD ["python", "logging_service.py"]
