FROM python:3.9-slim

WORKDIR /app
COPY analytics_service.py observer.py /app/
RUN apt-get update && apt-get install -y curl && pip install flask requests

EXPOSE 7003
CMD ["python", "analytics_service.py"]
