version: '3.8'
services:
  stock_monitor:
    build:
      context: .
      dockerfile: Dockerfile.stock_monitor
    image: basliel13/stock_monitor_api:stock_monitor
    depends_on:
      - logging_service
      - analytics_service
      - notification_service

  api_service:
    build:
      context: .
      dockerfile: Dockerfile.api_service
    image: basliel13/stock_monitor_api:api_service
    ports:
      - "5000:5000"
    depends_on:
      - stock_monitor

  logging_service:
    build:
      context: .
      dockerfile: Dockerfile.logging_service
    image: basliel13/stock_monitor_api:logging_service
    volumes:
      - logs:/logs

  analytics_service:
    build:
      context: .
      dockerfile: Dockerfile.analytics_service
    image: basliel13/stock_monitor_api:analytics_service

  notification_service:
    build:
      context: .
      dockerfile: Dockerfile.notification_service
    image: basliel13/stock_monitor_api:notification_service

volumes:
  logs:
